### PR TITLE
General Fixes | Python 3.10 Support

### PR DESCRIPTION
**Pull request by TheOnlyWayUp**
image

;)

### CODE REVIEW

**Comment by TheOnlyWayUp** [comment]
Found a few more minor issues, fixing :)

**Comment by TheOnlyWayUp** [comment]
Hmm, looks very python2-ish. A bit more info on package and language requirements on the readme would be nice

**Comment by TheOnlyWayUp** [comment]
The image doesn't seem to have an affect, I don't see any outgoing /science requests nor code execution on my client @0x44F

**Comment by 0x44F** [comment]
What client are you using?

**Comment by TheOnlyWayUp** [comment]
> What client are you using?

I'm using the discord desktop app for windows
```
Stable 144604 (1d8cb60)
Host 1.0.9006
Windows 10 64-Bit (10.0.22000)
```

**Pull request merged**
